// data.jsx — ข้อมูลจริงจาก Wongnai + Google Maps (100 ร้าน)
// Areas: สยาม · อารีย์ · ทองหล่อ · อโศก · พร้อมพงษ์

const AREAS = ["สยาม", "อารีย์", "ทองหล่อ", "อโศก", "พร้อมพงษ์"];

const FOOD_CATEGORIES = [
  "อาหารไทย", "อาหารญี่ปุ่น", "อาหารเกาหลี", "ชาบู/หม้อไฟ",
  "อาหารอิตาเลียน", "สเต๊กและอาหารตะวันตก", "อาหารนานาชาติ",
  "คาเฟ่และบรันช์", "อาหารทะเล", "อาหารจีนและติ่มซำ", "อาหารสุขภาพ",
];

const RESTAURANTS = [
  {
    id: "r1", name: "CoCoICHIBANYA", cuisine: "อาหารญี่ปุ่น", area: "สยาม",
    hue: 200, rating: 3.9, reviews: 170, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 0.4, capacity: 13, aiScore: 77,
    location: "สยามพารากอน ชั้น G", transit: "BTS สยาม", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=CoCoICHIBANYA+Siam+Paragon", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 81, price: 95, distance: 72, capacity: 68, dataCompleteness: 72, uniqueness: 75 },
    radar: { "รสชาติ": 83, "ความคุ้มค่า": 80, "การบริการ": 71, "บรรยากาศ": 81, "ความเข้ากันของกลุ่ม": 86 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.9★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "เปิดใหม่",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r2", name: "wwa cafe Siam Square", cuisine: "อาหารนานาชาติ", area: "สยาม",
    hue: 140, rating: 3.8, reviews: 30, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 0.6, capacity: 10, aiScore: 80,
    location: "Siam Square", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=wwa+cafe+Siam+Square", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 84, price: 95, distance: 79, capacity: 77, dataCompleteness: 68, uniqueness: 76 },
    radar: { "รสชาติ": 83, "ความคุ้มค่า": 66, "การบริการ": 79, "บรรยากาศ": 76, "ความเข้ากันของกลุ่ม": 81 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.8★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r3", name: "Tenjo Sushi & Yakiniku Premium Buffet", cuisine: "ชาบู/หม้อไฟ", area: "สยาม",
    hue: 190, rating: 3.7, reviews: 163, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 1.5, capacity: 12, aiScore: 77,
    location: "Siam Square One", transit: "BTS สยาม", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Tenjo+Sushi+Siam+Square+One", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 80, price: 76, distance: 84, capacity: 76, dataCompleteness: 68, uniqueness: 76 },
    radar: { "รสชาติ": 80, "ความคุ้มค่า": 73, "การบริการ": 74, "บรรยากาศ": 69, "ความเข้ากันของกลุ่ม": 81 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.7★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r4", name: "ร้านจากึมซอง", cuisine: "อาหารเกาหลี", area: "สยาม",
    hue: 0, rating: 4.1, reviews: 59, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 1.3, capacity: 21, aiScore: 81,
    location: "Siam Square One ชั้น 5", transit: "BTS สยาม", hours: "11:00-21:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Jagumsong+Siam+Square+One", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 79, price: 81, distance: 86, capacity: 74, dataCompleteness: 85, uniqueness: 84 },
    radar: { "รสชาติ": 78, "ความคุ้มค่า": 74, "การบริการ": 87, "บรรยากาศ": 77, "ความเข้ากันของกลุ่ม": 89 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.1★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r5", name: "สวนผัก โอ้กะจู๋", cuisine: "อาหารสุขภาพ", area: "สยาม",
    hue: 120, rating: 4.3, reviews: 371, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 1.0, capacity: 21, aiScore: 82,
    location: "Siam Square One ชั้น 3", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Organic+Kitchen+Siam+Square+One", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 89, price: 82, distance: 84, capacity: 70, dataCompleteness: 83, uniqueness: 89 },
    radar: { "รสชาติ": 83, "ความคุ้มค่า": 85, "การบริการ": 84, "บรรยากาศ": 84, "ความเข้ากันของกลุ่ม": 88 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.3★ จาก 371 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r6", name: "Gourmet Eats", cuisine: "อาหารนานาชาติ", area: "สยาม",
    hue: 140, rating: 4.0, reviews: 25, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 0.9, capacity: 11, aiScore: 82,
    location: "สยามพารากอน", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Gourmet+Eats+Siam+Paragon", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 87, price: 96, distance: 67, capacity: 73, dataCompleteness: 81, uniqueness: 87 },
    radar: { "รสชาติ": 78, "ความคุ้มค่า": 85, "การบริการ": 79, "บรรยากาศ": 80, "ความเข้ากันของกลุ่ม": 89 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r7", name: "Sukiya", cuisine: "ชาบู/หม้อไฟ", area: "สยาม",
    hue: 190, rating: 3.3, reviews: 3, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 0.6, capacity: 18, aiScore: 76,
    location: "MBK", transit: "BTS สนามกีฬาแห่งชาติ", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Sukiya+MBK+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 73, price: 99, distance: 76, capacity: 74, dataCompleteness: 61, uniqueness: 78 },
    radar: { "รสชาติ": 68, "ความคุ้มค่า": 65, "การบริการ": 58, "บรรยากาศ": 71, "ความเข้ากันของกลุ่ม": 61 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.3★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r8", name: "Pizza Hut", cuisine: "อาหารอิตาเลียน", area: "สยาม",
    hue: 8, rating: 3.4, reviews: 21, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 0.9, capacity: 12, aiScore: 76,
    location: "มาบุญครอง MBK", transit: "BTS สนามกีฬาแห่งชาติ", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Pizza+Hut+MBK+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 77, price: 96, distance: 82, capacity: 60, dataCompleteness: 64, uniqueness: 82 },
    radar: { "รสชาติ": 73, "ความคุ้มค่า": 70, "การบริการ": 72, "บรรยากาศ": 66, "ความเข้ากันของกลุ่ม": 73 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r9", name: "Boost Juice Bars", cuisine: "อาหารนานาชาติ", area: "สยาม",
    hue: 140, rating: 4.0, reviews: 4, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 2.4, capacity: 18, aiScore: 85,
    location: "BTS Siam", transit: "BTS สยาม", hours: "08:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Boost+Juice+BTS+Siam", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 80, price: 91, distance: 85, capacity: 79, dataCompleteness: 90, uniqueness: 93 },
    radar: { "รสชาติ": 84, "ความคุ้มค่า": 71, "การบริการ": 74, "บรรยากาศ": 79, "ความเข้ากันของกลุ่ม": 80 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r10", name: "Starbucks Siam Center", cuisine: "คาเฟ่และบรันช์", area: "สยาม",
    hue: 270, rating: 4.0, reviews: 2, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 2.1, capacity: 20, aiScore: 83,
    location: "Siam Center ชั้น 1", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Starbucks+Siam+Center", wongnaiLink: "https://www.wongnai.com/restaurants?regions=220",
    breakdown: { reviews: 78, price: 99, distance: 90, capacity: 79, dataCompleteness: 77, uniqueness: 75 },
    radar: { "รสชาติ": 75, "ความคุ้มค่า": 72, "การบริการ": 81, "บรรยากาศ": 75, "ความเข้ากันของกลุ่ม": 77 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r11", name: "บ้านพึงชม", cuisine: "อาหารไทย", area: "อารีย์",
    hue: 28, rating: 4.1, reviews: 235, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 1.2, capacity: 14, aiScore: 87,
    location: "อารีย์", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Baan+Phueng+Chom+Ari", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 92, price: 93, distance: 73, capacity: 93, dataCompleteness: 86, uniqueness: 78 },
    radar: { "รสชาติ": 80, "ความคุ้มค่า": 84, "การบริการ": 86, "บรรยากาศ": 87, "ความเข้ากันของกลุ่ม": 83 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.1★ จาก 235 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "BEST OF 2026",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r12", name: "Fishmonger", cuisine: "อาหารนานาชาติ", area: "อารีย์",
    hue: 140, rating: 4.4, reviews: 58, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 0.4, capacity: 24, aiScore: 78,
    location: "อารีย์", transit: "BTS อารีย์", hours: "11:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Fishmonger+Ari+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 90, price: 67, distance: 75, capacity: 61, dataCompleteness: 87, uniqueness: 85 },
    radar: { "รสชาติ": 92, "ความคุ้มค่า": 80, "การบริการ": 80, "บรรยากาศ": 83, "ความเข้ากันของกลุ่ม": 84 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r13", name: "Overseoul", cuisine: "อาหารเกาหลี", area: "อารีย์",
    hue: 0, rating: 4.2, reviews: 28, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 0.5, capacity: 17, aiScore: 86,
    location: "อารีย์", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Overseoul+Ari+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 94, price: 94, distance: 82, capacity: 68, dataCompleteness: 92, uniqueness: 84 },
    radar: { "รสชาติ": 82, "ความคุ้มค่า": 84, "การบริการ": 88, "บรรยากาศ": 84, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.2★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r14", name: "Lucky's Hungry", cuisine: "อาหารนานาชาติ", area: "อารีย์",
    hue: 140, rating: 4.0, reviews: 130, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 1.3, capacity: 24, aiScore: 79,
    location: "อารีย์", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Luckys+Hungry+Ari+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 76, price: 83, distance: 66, capacity: 85, dataCompleteness: 84, uniqueness: 83 },
    radar: { "รสชาติ": 87, "ความคุ้มค่า": 68, "การบริการ": 75, "บรรยากาศ": 77, "ความเข้ากันของกลุ่ม": 81 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r15", name: "Pink Typhoon Creative Pasta & Steak", cuisine: "สเต๊กและอาหารตะวันตก", area: "อารีย์",
    hue: 20, rating: 4.5, reviews: 23, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 2.3, capacity: 17, aiScore: 88,
    location: "อารีย์", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Pink+Typhoon+Ari+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 87, price: 79, distance: 90, capacity: 95, dataCompleteness: 83, uniqueness: 92 },
    radar: { "รสชาติ": 85, "ความคุ้มค่า": 95, "การบริการ": 90, "บรรยากาศ": 97, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.5★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r16", name: "คลั่งเนื้อ อารีย์ซอย 5", cuisine: "สเต๊กและอาหารตะวันตก", area: "อารีย์",
    hue: 20, rating: 4.5, reviews: 13, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 1.2, capacity: 25, aiScore: 80,
    location: "อารีย์ ซอย 5", transit: "BTS อารีย์", hours: "17:00-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Klang+Nuea+Ari+Soi+5", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 97, price: 48, distance: 70, capacity: 84, dataCompleteness: 81, uniqueness: 94 },
    radar: { "รสชาติ": 91, "ความคุ้มค่า": 83, "การบริการ": 94, "บรรยากาศ": 96, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.5★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r17", name: "Baimiang Healthy Shop ใบเมี่ยง", cuisine: "อาหารสุขภาพ", area: "อารีย์",
    hue: 120, rating: 4.2, reviews: 4, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 2.3, capacity: 25, aiScore: 86,
    location: "ลาวิลล่าอารีย์", transit: "BTS อารีย์", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Baimiang+Healthy+Ari+LaVilla", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 88, price: 94, distance: 66, capacity: 94, dataCompleteness: 77, uniqueness: 92 },
    radar: { "รสชาติ": 90, "ความคุ้มค่า": 79, "การบริการ": 76, "บรรยากาศ": 78, "ความเข้ากันของกลุ่ม": 94 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.2★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r18", name: "ปากหม้อ", cuisine: "อาหารไทย", area: "อารีย์",
    hue: 28, rating: 3.8, reviews: 12, priceTHB: 80,
    priceLabel: "฿ (ต่ำกว่า 100 บาท)", distanceKm: 0.5, capacity: 12, aiScore: 81,
    location: "อารีย์", transit: "BTS อารีย์", hours: "08:00-20:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Pak+Mo+Ari+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 73, price: 94, distance: 86, capacity: 75, dataCompleteness: 81, uniqueness: 88 },
    radar: { "รสชาติ": 72, "ความคุ้มค่า": 79, "การบริการ": 71, "บรรยากาศ": 79, "ความเข้ากันของกลุ่ม": 72 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.8★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r19", name: "The Key Room 72", cuisine: "อาหารนานาชาติ", area: "อารีย์",
    hue: 140, rating: 4.0, reviews: 1, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 0.3, capacity: 20, aiScore: 82,
    location: "อารีย์", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=The+Key+Room+72+Ari+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 81, price: 90, distance: 72, capacity: 76, dataCompleteness: 86, uniqueness: 93 },
    radar: { "รสชาติ": 77, "ความคุ้มค่า": 85, "การบริการ": 76, "บรรยากาศ": 81, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r20", name: "หอมด่วน", cuisine: "อาหารไทย", area: "อารีย์",
    hue: 28, rating: 4.0, reviews: 1, priceTHB: 80,
    priceLabel: "฿ (ต่ำกว่า 100 บาท)", distanceKm: 1.8, capacity: 6, aiScore: 80,
    location: "สีลม/อารีย์", transit: "BTS อารีย์", hours: "11:00-21:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=Hom+Duan+Ari+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=242",
    breakdown: { reviews: 81, price: 99, distance: 69, capacity: 82, dataCompleteness: 72, uniqueness: 75 },
    radar: { "รสชาติ": 78, "ความคุ้มค่า": 76, "การบริการ": 76, "บรรยากาศ": 76, "ความเข้ากันของกลุ่ม": 89 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r21", name: "Thong Grill Hide & Shabu Thonglor Soi 9", cuisine: "ชาบู/หม้อไฟ", area: "ทองหล่อ",
    hue: 190, rating: 4.9, reviews: 30, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 0.8, capacity: 10, aiScore: 83,
    location: "ทองหล่อ ซอย 9", transit: "BTS ทองหล่อ", hours: "17:00-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Thong+Grill+Hide+Shabu+Thonglor+Soi+9", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 99, price: 68, distance: 69, capacity: 76, dataCompleteness: 92, uniqueness: 90 },
    radar: { "รสชาติ": 94, "ความคุ้มค่า": 95, "การบริการ": 92, "บรรยากาศ": 96, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.9★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "#1 ชาบู/สุกี้ยากี้ ในกรุงเทพฯ",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r22", name: "Ginzado", cuisine: "อาหารญี่ปุ่น", area: "ทองหล่อ",
    hue: 200, rating: 4.4, reviews: 187, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 2.5, capacity: 18, aiScore: 82,
    location: "ทองหล่อ", transit: "BTS ทองหล่อ", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Ginzado+Thonglor+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 91, price: 66, distance: 67, capacity: 87, dataCompleteness: 88, uniqueness: 85 },
    radar: { "รสชาติ": 83, "ความคุ้มค่า": 73, "การบริการ": 85, "บรรยากาศ": 94, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "BEST OF 2026",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r23", name: "Yakiniku Master Shoutaian", cuisine: "อาหารญี่ปุ่น", area: "ทองหล่อ",
    hue: 200, rating: 4.4, reviews: 68, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 0.6, capacity: 23, aiScore: 77,
    location: "ทองหล่อ", transit: "BTS ทองหล่อ", hours: "17:30-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Yakiniku+Master+Shoutaian+Thonglor", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 86, price: 49, distance: 87, capacity: 69, dataCompleteness: 82, uniqueness: 87 },
    radar: { "รสชาติ": 96, "ความคุ้มค่า": 84, "การบริการ": 89, "บรรยากาศ": 90, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r24", name: "Kiani", cuisine: "อาหารเกาหลี", area: "ทองหล่อ",
    hue: 0, rating: 4.4, reviews: 280, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 2.2, capacity: 11, aiScore: 84,
    location: "ทองหล่อ", transit: "BTS ทองหล่อ", hours: "11:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Kiani+Thonglor+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 89, price: 87, distance: 86, capacity: 66, dataCompleteness: 93, uniqueness: 89 },
    radar: { "รสชาติ": 95, "ความคุ้มค่า": 90, "การบริการ": 93, "บรรยากาศ": 88, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.4★ จาก 280 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r25", name: "BlueSpice Cafe", cuisine: "อาหารนานาชาติ", area: "ทองหล่อ",
    hue: 140, rating: 4.1, reviews: 78, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 0.8, capacity: 23, aiScore: 85,
    location: "แกรนด์ เซ็นเตอร์ พ้อยต์ สุขุมวิท 55", transit: "BTS ทองหล่อ", hours: "07:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=BlueSpice+Cafe+Grand+Center+Point+Thonglor", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 87, price: 93, distance: 90, capacity: 75, dataCompleteness: 80, uniqueness: 86 },
    radar: { "รสชาติ": 79, "ความคุ้มค่า": 70, "การบริการ": 80, "บรรยากาศ": 89, "ความเข้ากันของกลุ่ม": 78 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.1★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r26", name: "Shugetsu Ramen", cuisine: "อาหารญี่ปุ่น", area: "ทองหล่อ",
    hue: 200, rating: 3.8, reviews: 101, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 1.7, capacity: 19, aiScore: 77,
    location: "The 49 Terrace", transit: "BTS ทองหล่อ", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Shugetsu+Ramen+Thonglor+49+Terrace", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 78, price: 87, distance: 65, capacity: 72, dataCompleteness: 79, uniqueness: 84 },
    radar: { "รสชาติ": 76, "ความคุ้มค่า": 69, "การบริการ": 81, "บรรยากาศ": 71, "ความเข้ากันของกลุ่ม": 79 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.8★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "#2 ราเมง ในกรุงเทพฯ",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r27", name: "Bo.lan", cuisine: "อาหารไทย", area: "ทองหล่อ",
    hue: 28, rating: 3.4, reviews: 28, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 1.3, capacity: 10, aiScore: 67,
    location: "ทองหล่อ", transit: "BTS ทองหล่อ", hours: "18:00-22:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=Bolan+Thai+Restaurant+Thonglor", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 63, price: 50, distance: 73, capacity: 71, dataCompleteness: 68, uniqueness: 80 },
    radar: { "รสชาติ": 63, "ความคุ้มค่า": 56, "การบริการ": 69, "บรรยากาศ": 68, "ความเข้ากันของกลุ่ม": 74 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r28", name: "Starita Bangkok", cuisine: "อาหารอิตาเลียน", area: "ทองหล่อ",
    hue: 8, rating: 4.2, reviews: 14, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 1.0, capacity: 16, aiScore: 83,
    location: "ทองหล่อ", transit: "BTS ทองหล่อ", hours: "11:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Starita+Bangkok+Thonglor", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 92, price: 47, distance: 81, capacity: 94, dataCompleteness: 83, uniqueness: 94 },
    radar: { "รสชาติ": 84, "ความคุ้มค่า": 82, "การบริการ": 77, "บรรยากาศ": 88, "ความเข้ากันของกลุ่ม": 89 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.2★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r29", name: "Kenji's Lab", cuisine: "อาหารญี่ปุ่น", area: "ทองหล่อ",
    hue: 200, rating: 4.2, reviews: 50, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 1.6, capacity: 19, aiScore: 83,
    location: "ทองหล่อ", transit: "BTS ทองหล่อ", hours: "17:30-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Kenjis+Lab+Thonglor+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 92, price: 75, distance: 77, capacity: 78, dataCompleteness: 82, uniqueness: 96 },
    radar: { "รสชาติ": 82, "ความคุ้มค่า": 82, "การบริการ": 86, "บรรยากาศ": 84, "ความเข้ากันของกลุ่ม": 84 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.2★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "BEST OF 2026",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r30", name: "LAVA Fire Grill (Steak, Wagyu)", cuisine: "สเต๊กและอาหารตะวันตก", area: "ทองหล่อ",
    hue: 20, rating: 4.3, reviews: 8, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 0.5, capacity: 8, aiScore: 83,
    location: "ทองหล่อ", transit: "BTS ทองหล่อ", hours: "17:00-23:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=LAVA+Fire+Grill+Thonglor+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=224",
    breakdown: { reviews: 94, price: 57, distance: 79, capacity: 88, dataCompleteness: 90, uniqueness: 79 },
    radar: { "รสชาติ": 91, "ความคุ้มค่า": 77, "การบริการ": 86, "บรรยากาศ": 87, "ความเข้ากันของกลุ่ม": 86 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.3★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r31", name: "กะเพราตาแป๊ะ", cuisine: "อาหารไทย", area: "อโศก",
    hue: 28, rating: 4.2, reviews: 129, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 1.2, capacity: 20, aiScore: 81,
    location: "อโศก", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:00-21:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Kaprao+Ta+Pae+Asok+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 86, price: 97, distance: 72, capacity: 72, dataCompleteness: 79, uniqueness: 80 },
    radar: { "รสชาติ": 79, "ความคุ้มค่า": 70, "การบริการ": 79, "บรรยากาศ": 85, "ความเข้ากันของกลุ่ม": 81 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.2★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r32", name: "Aesops Greek Restaurant & Rooftop", cuisine: "สเต๊กและอาหารตะวันตก", area: "อโศก",
    hue: 20, rating: 4.1, reviews: 102, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 1.5, capacity: 22, aiScore: 76,
    location: "Asok Sukhumvit 16", transit: "BTS อโศก/MRT สุขุมวิท", hours: "17:00-24:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Aesops+Greek+Restaurant+Asok+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 84, price: 69, distance: 85, capacity: 60, dataCompleteness: 77, uniqueness: 80 },
    radar: { "รสชาติ": 89, "ความคุ้มค่า": 80, "การบริการ": 77, "บรรยากาศ": 78, "ความเข้ากันของกลุ่ม": 91 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.1★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r33", name: "Izakaya Konoji", cuisine: "อาหารญี่ปุ่น", area: "อโศก",
    hue: 200, rating: 4.6, reviews: 20, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 1.3, capacity: 14, aiScore: 91,
    location: "โรงแรมเบสท์ คอมฟอร์ท", transit: "BTS อโศก/MRT สุขุมวิท", hours: "17:00-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Izakaya+Konoji+Asok+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 97, price: 79, distance: 84, capacity: 92, dataCompleteness: 98, uniqueness: 90 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 94, "การบริการ": 91, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 92 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.6★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r34", name: "Orchid Cafe", cuisine: "อาหารนานาชาติ", area: "อโศก",
    hue: 140, rating: 4.1, reviews: 55, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 2.3, capacity: 18, aiScore: 80,
    location: "โรงแรมเชอราตันแกรนด์สุขุมวิท", transit: "BTS อโศก/MRT สุขุมวิท", hours: "06:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Orchid+Cafe+Sheraton+Grande+Sukhumvit", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 92, price: 54, distance: 73, capacity: 88, dataCompleteness: 78, uniqueness: 84 },
    radar: { "รสชาติ": 88, "ความคุ้มค่า": 76, "การบริการ": 77, "บรรยากาศ": 80, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.1★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r35", name: "Seasonal Tastes", cuisine: "อาหารนานาชาติ", area: "อโศก",
    hue: 140, rating: 3.9, reviews: 50, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 1.2, capacity: 22, aiScore: 76,
    location: "The Westin Grande Sukhumvit", transit: "BTS อโศก/MRT สุขุมวิท", hours: "06:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Seasonal+Tastes+Westin+Grande+Sukhumvit", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 79, price: 49, distance: 78, capacity: 86, dataCompleteness: 78, uniqueness: 83 },
    radar: { "รสชาติ": 81, "ความคุ้มค่า": 77, "การบริการ": 76, "บรรยากาศ": 72, "ความเข้ากันของกลุ่ม": 79 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.9★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r36", name: "JHOL Coastal Indian Cuisine", cuisine: "อาหารนานาชาติ", area: "อโศก",
    hue: 140, rating: 4.4, reviews: 72, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 1.9, capacity: 10, aiScore: 82,
    location: "สุขุมวิท 18", transit: "BTS อโศก/MRT สุขุมวิท", hours: "12:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=JHOL+Coastal+Indian+Cuisine+Sukhumvit+18", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 95, price: 62, distance: 65, capacity: 82, dataCompleteness: 88, uniqueness: 93 },
    radar: { "รสชาติ": 95, "ความคุ้มค่า": 85, "การบริการ": 93, "บรรยากาศ": 96, "ความเข้ากันของกลุ่ม": 96 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r37", name: "Chu Chocolate Bar & Cafe", cuisine: "คาเฟ่และบรันช์", area: "อโศก",
    hue: 270, rating: 3.9, reviews: 244, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 2.5, capacity: 17, aiScore: 79,
    location: "Exchange Tower", transit: "BTS อโศก/MRT สุขุมวิท", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Chu+Chocolate+Bar+Cafe+Exchange+Tower+Asok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 81, price: 93, distance: 80, capacity: 61, dataCompleteness: 82, uniqueness: 87 },
    radar: { "รสชาติ": 78, "ความคุ้มค่า": 75, "การบริการ": 81, "บรรยากาศ": 74, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.9★ จาก 244 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r38", name: "Umenohana", cuisine: "อาหารญี่ปุ่น", area: "อโศก",
    hue: 200, rating: 3.9, reviews: 10, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 1.0, capacity: 10, aiScore: 75,
    location: "Solaria", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Umenohana+Solaria+Asok+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 86, price: 51, distance: 79, capacity: 71, dataCompleteness: 72, uniqueness: 89 },
    radar: { "รสชาติ": 77, "ความคุ้มค่า": 75, "การบริการ": 75, "บรรยากาศ": 75, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.9★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "บรรยากาศดี เหมาะสำหรับมื้ออาหารกลุ่มเล็ก",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r39", name: "Baimiang Healthy Shop Singha Complex", cuisine: "อาหารสุขภาพ", area: "อโศก",
    hue: 120, rating: 3.5, reviews: 10, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 2.4, capacity: 23, aiScore: 78,
    location: "Singha Complex", transit: "BTS อโศก/MRT สุขุมวิท", hours: "10:00-21:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Baimiang+Healthy+Singha+Complex+Asok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 67, price: 99, distance: 65, capacity: 94, dataCompleteness: 65, uniqueness: 85 },
    radar: { "รสชาติ": 70, "ความคุ้มค่า": 62, "การบริการ": 72, "บรรยากาศ": 65, "ความเข้ากันของกลุ่ม": 66 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.5★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r40", name: "Starbucks Rasa Two", cuisine: "คาเฟ่และบรันช์", area: "อโศก",
    hue: 270, rating: 3.9, reviews: 23, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 1.6, capacity: 14, aiScore: 82,
    location: "Rasa Two", transit: "BTS อโศก/MRT สุขุมวิท", hours: "07:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Starbucks+Rasa+Two+Asok+Bangkok", wongnaiLink: "https://www.wongnai.com/restaurants?regions=225",
    breakdown: { reviews: 88, price: 91, distance: 83, capacity: 73, dataCompleteness: 82, uniqueness: 73 },
    radar: { "รสชาติ": 84, "ความคุ้มค่า": 71, "การบริการ": 82, "บรรยากาศ": 77, "ความเข้ากันของกลุ่ม": 78 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.9★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "#1 กาแฟ/ชา ในกรุงเทพฯ",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r41", name: "El Toro Steakhouse", cuisine: "สเต๊กและอาหารตะวันตก", area: "พร้อมพงษ์",
    hue: 20, rating: 4.1, reviews: 247, priceTHB: 1200,
    priceLabel: "฿฿฿฿฿ (1,000+ บาท)", distanceKm: 1.6, capacity: 12, aiScore: 74,
    location: "พร้อมพงษ์", transit: "BTS พร้อมพงษ์", hours: "12:00-22:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=El+Toro+Steakhouse+Phrom+Phong+Bangkok", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 86, price: 50, distance: 83, capacity: 61, dataCompleteness: 82, uniqueness: 78 },
    radar: { "รสชาติ": 86, "ความคุ้มค่า": 79, "การบริการ": 80, "บรรยากาศ": 87, "ความเข้ากันของกลุ่ม": 83 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.1★ จาก 247 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "#1 ร้านสเต๊ก ในกรุงเทพฯ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r42", name: "Custard Nakamura", cuisine: "คาเฟ่และบรันช์", area: "พร้อมพงษ์",
    hue: 270, rating: 4.2, reviews: 540, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 2.2, capacity: 19, aiScore: 86,
    location: "พร้อมพงษ์", transit: "BTS พร้อมพงษ์", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Custard+Nakamura+Phrom+Phong+Bangkok", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 82, price: 89, distance: 76, capacity: 94, dataCompleteness: 89, uniqueness: 82 },
    radar: { "รสชาติ": 89, "ความคุ้มค่า": 80, "การบริการ": 77, "บรรยากาศ": 86, "ความเข้ากันของกลุ่ม": 89 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.2★ จาก 540 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r43", name: "298 (NIKU-YA) Yakiniku", cuisine: "อาหารญี่ปุ่น", area: "พร้อมพงษ์",
    hue: 200, rating: 5.0, reviews: 2, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 1.3, capacity: 21, aiScore: 85,
    location: "Sukhumvit 41", transit: "BTS พร้อมพงษ์", hours: "17:00-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=298+Niku+Ya+Yakiniku+Sukhumvit+41", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 99, price: 69, distance: 78, capacity: 71, dataCompleteness: 99, uniqueness: 96 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 93, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 5.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r44", name: "SaladStop! The Emsphere", cuisine: "อาหารสุขภาพ", area: "พร้อมพงษ์",
    hue: 120, rating: 5.0, reviews: 2, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 1.4, capacity: 17, aiScore: 90,
    location: "The Emsphere", transit: "BTS พร้อมพงษ์", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=SaladStop+Emsphere+Phrom+Phong", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 97, price: 96, distance: 79, capacity: 75, dataCompleteness: 99, uniqueness: 98 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 95, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 5.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r45", name: "รุ่งเรือง (ตั๋ง) ก๋วยเตี๋ยวหมู สุขุมวิท 26", cuisine: "อาหารไทย", area: "พร้อมพงษ์",
    hue: 28, rating: 4.1, reviews: 427, priceTHB: 80,
    priceLabel: "฿ (ต่ำกว่า 100 บาท)", distanceKm: 1.5, capacity: 21, aiScore: 84,
    location: "สุขุมวิท 26", transit: "BTS พร้อมพงษ์", hours: "07:00-17:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Rung+Ruang+Noodle+Sukhumvit+26+Bangkok", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 87, price: 99, distance: 84, capacity: 77, dataCompleteness: 72, uniqueness: 86 },
    radar: { "รสชาติ": 85, "ความคุ้มค่า": 73, "การบริการ": 75, "บรรยากาศ": 79, "ความเข้ากันของกลุ่ม": 90 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.1★ จาก 427 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r46", name: "Starbucks Emporium Atelier", cuisine: "คาเฟ่และบรันช์", area: "พร้อมพงษ์",
    hue: 270, rating: 3.5, reviews: 6, priceTHB: 175,
    priceLabel: "฿฿ (100-250 บาท)", distanceKm: 1.5, capacity: 25, aiScore: 74,
    location: "Emporium Atelier", transit: "BTS พร้อมพงษ์", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Starbucks+Emporium+Atelier+Phrom+Phong", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 65, price: 90, distance: 74, capacity: 74, dataCompleteness: 73, uniqueness: 79 },
    radar: { "รสชาติ": 76, "ความคุ้มค่า": 62, "การบริการ": 66, "บรรยากาศ": 74, "ความเข้ากันของกลุ่ม": 76 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.5★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r47", name: "KELLY'S Another 41", cuisine: "อาหารญี่ปุ่น", area: "พร้อมพงษ์",
    hue: 200, rating: 5.0, reviews: 1, priceTHB: 750,
    priceLabel: "฿฿฿฿ (500+ บาท)", distanceKm: 0.8, capacity: 20, aiScore: 87,
    location: "Sukhumvit 41", transit: "BTS พร้อมพงษ์", hours: "17:00-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Kellys+Another+41+Sukhumvit+41", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 99, price: 73, distance: 74, capacity: 76, dataCompleteness: 99, uniqueness: 99 },
    radar: { "รสชาติ": 96, "ความคุ้มค่า": 91, "การบริการ": 97, "บรรยากาศ": 95, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 5.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r48", name: "เนื้อแคมป์ไฟ ข้าวหน้าเนื้อไฟลุก", cuisine: "อาหารนานาชาติ", area: "พร้อมพงษ์",
    hue: 140, rating: 4.3, reviews: 10, priceTHB: 375,
    priceLabel: "฿฿฿ (251-500 บาท)", distanceKm: 0.4, capacity: 19, aiScore: 85,
    location: "ปรีดีพนมยงค์ 26", transit: "BTS พร้อมพงษ์", hours: "11:00-21:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Nuea+Camp+Fire+Pridi+Phanomyong+26", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 87, price: 89, distance: 72, capacity: 83, dataCompleteness: 84, uniqueness: 95 },
    radar: { "รสชาติ": 85, "ความคุ้มค่า": 71, "การบริการ": 89, "บรรยากาศ": 88, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 4.3★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r49", name: "PACAMARA Tops Food Hall", cuisine: "คาเฟ่และบรันช์", area: "พร้อมพงษ์",
    hue: 270, rating: 3.5, reviews: 4, priceTHB: 80,
    priceLabel: "฿ (ต่ำกว่า 100 บาท)", distanceKm: 2.4, capacity: 14, aiScore: 80,
    location: "Tops Food Hall Sukhumvit 39", transit: "BTS พร้อมพงษ์", hours: "08:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=PACAMARA+Tops+Food+Hall+Sukhumvit+39", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 80, price: 95, distance: 65, capacity: 78, dataCompleteness: 79, uniqueness: 85 },
    radar: { "รสชาติ": 72, "ความคุ้มค่า": 69, "การบริการ": 67, "บรรยากาศ": 66, "ความเข้ากันของกลุ่ม": 66 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 3.5★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r50", name: "กินเส้นก๋วยเตี๋ยว ฮาลาล", cuisine: "อาหารไทย", area: "พร้อมพงษ์",
    hue: 28, rating: 5.0, reviews: 3, priceTHB: 80,
    priceLabel: "฿ (ต่ำกว่า 100 บาท)", distanceKm: 1.6, capacity: 22, aiScore: 87,
    location: "สุขุมวิท 71", transit: "BTS พร้อมพงษ์", hours: "09:00-20:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Kin+Sen+Kwayteow+Halal+Sukhumvit+71", wongnaiLink: "https://www.wongnai.com/businesses?regions=226&regions=244",
    breakdown: { reviews: 96, price: 96, distance: 69, capacity: 79, dataCompleteness: 92, uniqueness: 90 },
    radar: { "รสชาติ": 98, "ความคุ้มค่า": 88, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Wongnai"],
    reasons: [
      "คะแนน 5.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r51", name: "จากึมซอง สยามสแควร์ วัน", cuisine: "อาหารเกาหลี", area: "สยาม",
    hue: 0, rating: 4.9, reviews: 3472, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 1.7, capacity: 22, aiScore: 92,
    location: "388 ชั้น 5 ห้อง SS5016 อาคารสยามสแควร์วัน", transit: "BTS สยาม", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=จากึมซอง+สยามสแควร์+วัน", wongnaiLink: "https://maps.google.com/maps/search/จากึมซอง+สยามสแควร์",
    breakdown: { reviews: 99, price: 92, distance: 83, capacity: 87, dataCompleteness: 98, uniqueness: 90 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 95, "การบริการ": 90, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 96 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 3,472 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ยอดนิยมมาก ต้องจอง",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r52", name: "Piranya@Siam ปิรันย่า@สยาม", cuisine: "อาหารไทย", area: "สยาม",
    hue: 28, rating: 4.8, reviews: 1462, priceTHB: 150,
    priceLabel: "฿1-200 บาท", distanceKm: 0.9, capacity: 17, aiScore: 88,
    location: "430/27 สยามสแควร์ ซอย 9 ถ. พระรามที่ 1", transit: "BTS สยาม", hours: "10:45-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Piranya+Siam+Square", wongnaiLink: "https://maps.google.com/maps/search/Piranya+Siam",
    breakdown: { reviews: 93, price: 94, distance: 65, capacity: 86, dataCompleteness: 99, uniqueness: 91 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 95, "การบริการ": 95, "บรรยากาศ": 94, "ความเข้ากันของกลุ่ม": 92 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,462 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ราคาถูก ย่านสยาม",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r53", name: "เดอะ การะเกด The karaked Siam Square One", cuisine: "อาหารไทย", area: "สยาม",
    hue: 28, rating: 4.7, reviews: 666, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 0.4, capacity: 12, aiScore: 86,
    location: "Siam Square One 388 ชั้น 4", transit: "BTS สยาม", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=The+karaked+Siam+Square+One", wongnaiLink: "https://maps.google.com/maps/search/The+karaked+Siam+Square",
    breakdown: { reviews: 97, price: 89, distance: 78, capacity: 67, dataCompleteness: 94, uniqueness: 91 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 83, "การบริการ": 90, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 93 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.7★ จาก 666 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "บรรยากาศดี แอร์เย็น",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r54", name: "Miss Siam Restaurant ห้องอาหารมิสสยาม", cuisine: "อาหารไทย", area: "สยาม",
    hue: 28, rating: 4.7, reviews: 49, priceTHB: 1100,
    priceLabel: "฿1,000-1,200 บาท", distanceKm: 0.5, capacity: 12, aiScore: 86,
    location: "400 ถ. พญาไท", transit: "BTS สยาม", hours: "11:30-22:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=Miss+Siam+Restaurant+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Miss+Siam+Restaurant",
    breakdown: { reviews: 98, price: 65, distance: 68, capacity: 89, dataCompleteness: 97, uniqueness: 93 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 91, "การบริการ": 90, "บรรยากาศ": 96, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.7★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "ห้องอาหารระดับบน",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r55", name: "Wisdom International Buffet Siam Paragon", cuisine: "อาหารนานาชาติ", area: "สยาม",
    hue: 140, rating: 4.3, reviews: 1242, priceTHB: 1200,
    priceLabel: "฿800-1,600 บาท", distanceKm: 1.4, capacity: 20, aiScore: 72,
    location: "ชั้น 4 Food Passage สยามพารากอน", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Wisdom+International+Buffet+Siam+Paragon", wongnaiLink: "https://maps.google.com/maps/search/Wisdom+International+Buffet+Siam",
    breakdown: { reviews: 81, price: 49, distance: 72, capacity: 61, dataCompleteness: 84, uniqueness: 89 },
    radar: { "รสชาติ": 90, "ความคุ้มค่า": 72, "การบริการ": 90, "บรรยากาศ": 92, "ความเข้ากันของกลุ่ม": 86 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,242 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "บุฟเฟต์หลากหลาย",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r56", name: "พาสต้าอาม่า สยามเซ็นเตอร์", cuisine: "อาหารอิตาเลียน", area: "สยาม",
    hue: 8, rating: 4.9, reviews: 4763, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 1.2, capacity: 23, aiScore: 91,
    location: "สยามเซ็นเตอร์ ชั้น 2 979 ถ. พระรามที่ 1", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=พาสต้าอาม่า+สยามเซ็นเตอร์", wongnaiLink: "https://maps.google.com/maps/search/พาสต้าอาม่า+สยาม",
    breakdown: { reviews: 99, price: 85, distance: 80, capacity: 82, dataCompleteness: 98, uniqueness: 99 },
    radar: { "รสชาติ": 98, "ความคุ้มค่า": 93, "การบริการ": 99, "บรรยากาศ": 93, "ความเข้ากันของกลุ่ม": 98 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 4,763 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ยอดนิยมมาก",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r57", name: "ต้นโอ๊ก", cuisine: "อาหารไทย", area: "สยาม",
    hue: 28, rating: 4.5, reviews: 305, priceTHB: 150,
    priceLabel: "฿1-200 บาท", distanceKm: 2.2, capacity: 22, aiScore: 86,
    location: "432/5 สยามสแควร์ ซอย 9", transit: "BTS สยาม", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=ต้นโอ๊ก+สยามสแควร์", wongnaiLink: "https://maps.google.com/maps/search/ต้นโอ๊ก+สยามสแควร์",
    breakdown: { reviews: 86, price: 99, distance: 67, capacity: 80, dataCompleteness: 90, uniqueness: 96 },
    radar: { "รสชาติ": 90, "ความคุ้มค่า": 78, "การบริการ": 94, "บรรยากาศ": 90, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.5★ จาก 305 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "ราคาถูกในย่านสยาม",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r58", name: "White Flower Factory ครัวดอกไม้ขาว", cuisine: "อาหารไทย", area: "สยาม",
    hue: 28, rating: 4.6, reviews: 1520, priceTHB: 500,
    priceLabel: "฿400-600 บาท", distanceKm: 2.2, capacity: 21, aiScore: 88,
    location: "Unit SS4009 388 ถ. พระรามที่ 1", transit: "BTS สยาม", hours: "10:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=White+Flower+Factory+Siam+Square", wongnaiLink: "https://maps.google.com/maps/search/White+Flower+Factory+Siam",
    breakdown: { reviews: 99, price: 89, distance: 89, capacity: 63, dataCompleteness: 91, uniqueness: 99 },
    radar: { "รสชาติ": 91, "ความคุ้มค่า": 94, "การบริการ": 86, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 96 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,520 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "วิวรถไฟฟ้า ร้านใหญ่",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r59", name: "Nabezo Premium Siam Paragon", cuisine: "ชาบู/หม้อไฟ", area: "สยาม",
    hue: 190, rating: 4.9, reviews: 456, priceTHB: 1200,
    priceLabel: "฿1,000+ บาท", distanceKm: 2.4, capacity: 17, aiScore: 85,
    location: "ชั้น G สยามพารากอน", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Nabezo+Premium+Siam+Paragon", wongnaiLink: "https://maps.google.com/maps/search/Nabezo+Siam+Paragon",
    breakdown: { reviews: 99, price: 47, distance: 82, capacity: 86, dataCompleteness: 94, uniqueness: 99 },
    radar: { "รสชาติ": 96, "ความคุ้มค่า": 86, "การบริการ": 97, "บรรยากาศ": 93, "ความเข้ากันของกลุ่ม": 97 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.9★ จาก 456 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "ชาบูพรีเมียม",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r60", name: "Tum Factory Siam Square One", cuisine: "อาหารไทย", area: "สยาม",
    hue: 28, rating: 4.0, reviews: 94, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 0.9, capacity: 23, aiScore: 85,
    location: "ชั้น 4 ห้อง SS4023 Siam Square One", transit: "BTS สยาม", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Tum+Factory+Siam+Square+One", wongnaiLink: "https://maps.google.com/maps/search/Tum+Factory+Siam+Square+One",
    breakdown: { reviews: 90, price: 90, distance: 79, capacity: 95, dataCompleteness: 74, uniqueness: 75 },
    radar: { "รสชาติ": 81, "ความคุ้มค่า": 71, "การบริการ": 81, "บรรยากาศ": 82, "ความเข้ากันของกลุ่ม": 79 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.0★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "ราคาดีในย่านนี้",
      "ตั้งอยู่ย่านสยาม เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r61", name: "Karimaki", cuisine: "อาหารนานาชาติ", area: "อารีย์",
    hue: 140, rating: 4.8, reviews: 600, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 2.0, capacity: 18, aiScore: 92,
    location: "โครงการสนั่นนภา ซอยอารีย์ 1", transit: "BTS อารีย์", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Karimaki+Ari+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Karimaki+Ari",
    breakdown: { reviews: 99, price: 92, distance: 83, capacity: 91, dataCompleteness: 91, uniqueness: 89 },
    radar: { "รสชาติ": 98, "ความคุ้มค่า": 95, "การบริการ": 95, "บรรยากาศ": 95, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.8★ จาก 600 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "บรรยากาศดี ร้านสวย",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r62", name: "โกปี๊ฮับ ไพรม์ อารีย์", cuisine: "อาหารจีนและติ่มซำ", area: "อารีย์",
    hue: 350, rating: 4.8, reviews: 3429, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 2.5, capacity: 16, aiScore: 89,
    location: "33 ซอยอารีย์ 2", transit: "BTS อารีย์", hours: "07:00-14:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=โกปี๊ฮับ+ไพรม์+อารีย์", wongnaiLink: "https://maps.google.com/maps/search/โกปี๊ฮับ+อารีย์",
    breakdown: { reviews: 98, price: 95, distance: 72, capacity: 86, dataCompleteness: 89, uniqueness: 91 },
    radar: { "รสชาติ": 96, "ความคุ้มค่า": 95, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 3,429 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ติ่มซำยอดนิยม เปิดเช้า",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r63", name: "Brooks brunch & bar Ari", cuisine: "คาเฟ่และบรันช์", area: "อารีย์",
    hue: 270, rating: 4.8, reviews: 1771, priceTHB: 700,
    priceLabel: "฿400-1,000 บาท", distanceKm: 1.9, capacity: 14, aiScore: 85,
    location: "18 ซอยอารีย์ 4 ฝั่งเหนือ", transit: "BTS อารีย์", hours: "08:30-16:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Brooks+brunch+bar+Ari+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Brooks+brunch+Ari",
    breakdown: { reviews: 92, price: 71, distance: 81, capacity: 81, dataCompleteness: 92, uniqueness: 93 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 95, "การบริการ": 89, "บรรยากาศ": 98, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,771 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "บรันช์ยอดนิยม",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r64", name: "ข้าวเหนียว", cuisine: "อาหารไทย", area: "อารีย์",
    hue: 28, rating: 4.6, reviews: 295, priceTHB: 500,
    priceLabel: "฿400-600 บาท", distanceKm: 1.7, capacity: 14, aiScore: 88,
    location: "ซอยอารีย์สัมพันธ์ 7", transit: "BTS อารีย์", hours: "11:00-21:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=ข้าวเหนียว+อารีย์สัมพันธ์", wongnaiLink: "https://maps.google.com/maps/search/ข้าวเหนียว+อารีย์",
    breakdown: { reviews: 95, price: 85, distance: 84, capacity: 85, dataCompleteness: 88, uniqueness: 92 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 87, "การบริการ": 97, "บรรยากาศ": 96, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.6★ จาก 295 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "อาหารเหนือ บรรยากาศดี",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r65", name: "เล ลาว ร้านส้มตำรางวัลมิชลิน 5 ปีซ้อน", cuisine: "อาหารไทย", area: "อารีย์",
    hue: 28, rating: 4.5, reviews: 2451, priceTHB: 500,
    priceLabel: "฿400-600 บาท", distanceKm: 0.7, capacity: 11, aiScore: 83,
    location: "65 ซ. พหลโยธิน 7", transit: "BTS อารีย์", hours: "10:30-21:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=เล+ลาว+อารีย์+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/เล+ลาว+อารีย์",
    breakdown: { reviews: 92, price: 84, distance: 72, capacity: 65, dataCompleteness: 93, uniqueness: 92 },
    radar: { "รสชาติ": 86, "ความคุ้มค่า": 95, "การบริการ": 93, "บรรยากาศ": 97, "ความเข้ากันของกลุ่ม": 88 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 2,451 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "มิชลินไกด์ 5 ปีติดต่อกัน",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r66", name: "Lucky's Hungry สาขา HAUS อารีย์", cuisine: "อาหารนานาชาติ", area: "อารีย์",
    hue: 140, rating: 4.7, reviews: 1522, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 0.7, capacity: 20, aiScore: 90,
    location: "9/1 ซ. อารีย์ 3", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Luckys+Hungry+HAUS+Ari+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Luckys+Hungry+Ari",
    breakdown: { reviews: 98, price: 94, distance: 76, capacity: 87, dataCompleteness: 89, uniqueness: 97 },
    radar: { "รสชาติ": 92, "ความคุ้มค่า": 95, "การบริการ": 92, "บรรยากาศ": 97, "ความเข้ากันของกลุ่ม": 94 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,522 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ยอดนิยม คุ้มค่า",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r67", name: "แซ่บสุดใจ อารีย์", cuisine: "อาหารไทย", area: "อารีย์",
    hue: 28, rating: 4.8, reviews: 160, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 1.5, capacity: 17, aiScore: 89,
    location: "466/18 ถ. พหลโยธิน", transit: "BTS อารีย์", hours: "11:00-05:30",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=แซ่บสุดใจ+อารีย์", wongnaiLink: "https://maps.google.com/maps/search/แซ่บสุดใจ+อารีย์",
    breakdown: { reviews: 95, price: 90, distance: 79, capacity: 76, dataCompleteness: 99, uniqueness: 99 },
    radar: { "รสชาติ": 95, "ความคุ้มค่า": 81, "การบริการ": 99, "บรรยากาศ": 97, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.8★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "เปิดดึก ราคาไม่แพง",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r68", name: "Fishmonger Ari", cuisine: "อาหารนานาชาติ", area: "อารีย์",
    hue: 140, rating: 4.4, reviews: 1011, priceTHB: 500,
    priceLabel: "฿400-600 บาท", distanceKm: 1.1, capacity: 19, aiScore: 87,
    location: "10/6 ซอยอารีย์ 4", transit: "BTS อารีย์", hours: "12:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Fishmonger+Ari+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Fishmonger+Ari",
    breakdown: { reviews: 96, price: 83, distance: 79, capacity: 79, dataCompleteness: 87, uniqueness: 97 },
    radar: { "รสชาติ": 89, "ความคุ้มค่า": 88, "การบริการ": 81, "บรรยากาศ": 85, "ความเข้ากันของกลุ่ม": 95 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,011 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ซีฟู้ดยอดนิยม",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r69", name: "บ้านพึงชม", cuisine: "อาหารไทย", area: "อารีย์",
    hue: 28, rating: 4.2, reviews: 1620, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 2.1, capacity: 10, aiScore: 82,
    location: "38 ซ. พหลโยธิน 7", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=บ้านพึงชม+อารีย์", wongnaiLink: "https://maps.google.com/maps/search/บ้านพึงชม+อารีย์",
    breakdown: { reviews: 91, price: 91, distance: 65, capacity: 63, dataCompleteness: 93, uniqueness: 96 },
    radar: { "รสชาติ": 92, "ความคุ้มค่า": 78, "การบริการ": 88, "บรรยากาศ": 90, "ความเข้ากันของกลุ่ม": 86 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,620 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อาหารไทยยอดนิยม",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r70", name: "Overseoul", cuisine: "อาหารเกาหลี", area: "อารีย์",
    hue: 0, rating: 4.2, reviews: 10, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 0.5, capacity: 18, aiScore: 79,
    location: "ซอยอารีย์", transit: "BTS อารีย์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Overseoul+Ari+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Overseoul+Ari",
    breakdown: { reviews: 83, price: 86, distance: 85, capacity: 62, dataCompleteness: 83, uniqueness: 78 },
    radar: { "รสชาติ": 91, "ความคุ้มค่า": 83, "การบริการ": 76, "บรรยากาศ": 87, "ความเข้ากันของกลุ่ม": 90 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.2★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "พื้นที่กว้างเหมาะสำหรับกลุ่มใหญ่ ไม่ต้องแยกโต๊ะ",
      "ตั้งอยู่ย่านอารีย์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r71", name: "ครัวเจียงใหม่ ทองหล่อ", cuisine: "อาหารไทย", area: "ทองหล่อ",
    hue: 28, rating: 4.8, reviews: 2737, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 1.3, capacity: 15, aiScore: 88,
    location: "125/24 ถ. ทองหล่อ", transit: "BTS ทองหล่อ", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=ครัวเจียงใหม่+ทองหล่อ", wongnaiLink: "https://maps.google.com/maps/search/ครัวเจียงใหม่+ทองหล่อ",
    breakdown: { reviews: 99, price: 91, distance: 70, capacity: 76, dataCompleteness: 98, uniqueness: 89 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 90, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 2,737 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อาหารเหนือยอดนิยม",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r72", name: "Supanniga Eating Room Thonglor", cuisine: "อาหารไทย", area: "ทองหล่อ",
    hue: 28, rating: 4.4, reviews: 1727, priceTHB: 1000,
    priceLabel: "฿400-1,600 บาท", distanceKm: 1.9, capacity: 17, aiScore: 81,
    location: "160/11 ถ. ทองหล่อ", transit: "BTS ทองหล่อ", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Supanniga+Eating+Room+Thonglor", wongnaiLink: "https://maps.google.com/maps/search/Supanniga+Thonglor",
    breakdown: { reviews: 95, price: 66, distance: 67, capacity: 85, dataCompleteness: 80, uniqueness: 85 },
    radar: { "รสชาติ": 87, "ความคุ้มค่า": 90, "การบริการ": 81, "บรรยากาศ": 89, "ความเข้ากันของกลุ่ม": 94 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,727 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ห้องทานข้าวสุพรรณิการ์",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r73", name: "NICO NICO Café & Brunch Place", cuisine: "คาเฟ่และบรันช์", area: "ทองหล่อ",
    hue: 270, rating: 4.5, reviews: 424, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 1.0, capacity: 21, aiScore: 89,
    location: "555 ตึก DM Home ถ. ทองหล่อ", transit: "BTS ทองหล่อ", hours: "07:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=NICO+NICO+Cafe+Brunch+Thonglor", wongnaiLink: "https://maps.google.com/maps/search/NICO+NICO+Cafe+Thonglor",
    breakdown: { reviews: 92, price: 98, distance: 65, capacity: 95, dataCompleteness: 93, uniqueness: 88 },
    radar: { "รสชาติ": 94, "ความคุ้มค่า": 82, "การบริการ": 92, "บรรยากาศ": 85, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.5★ จาก 424 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "บรันช์ยอดนิยม",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r74", name: "Kiani Korean Restaurant Thonglor", cuisine: "อาหารเกาหลี", area: "ทองหล่อ",
    hue: 0, rating: 4.8, reviews: 1264, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 1.9, capacity: 11, aiScore: 86,
    location: "90 Fifty fifth Thonglor Building ถ. ทองหล่อ", transit: "BTS ทองหล่อ", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Kiani+Korean+Restaurant+Thonglor", wongnaiLink: "https://maps.google.com/maps/search/Kiani+Thonglor",
    breakdown: { reviews: 99, price: 86, distance: 68, capacity: 75, dataCompleteness: 94, uniqueness: 95 },
    radar: { "รสชาติ": 97, "ความคุ้มค่า": 95, "การบริการ": 93, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,264 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "เกาหลียอดนิยม",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r75", name: "อีหล่า อีสานกายะ ทองหล่อ สาขา 2", cuisine: "อาหารไทย", area: "ทองหล่อ",
    hue: 28, rating: 4.7, reviews: 855, priceTHB: 700,
    priceLabel: "฿200-1,200 บาท", distanceKm: 2.5, capacity: 13, aiScore: 86,
    location: "187 ซ. สุขุมวิท 63", transit: "BTS ทองหล่อ", hours: "16:00-04:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=อีหล่า+อีสานกายะ+ทองหล่อ", wongnaiLink: "https://maps.google.com/maps/search/อีหล่า+อีสานกายะ+ทองหล่อ",
    breakdown: { reviews: 99, price: 75, distance: 66, capacity: 83, dataCompleteness: 90, uniqueness: 95 },
    radar: { "รสชาติ": 96, "ความคุ้มค่า": 93, "การบริการ": 89, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.7★ จาก 855 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "เปิดดึก บรรยากาศสนุก",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r76", name: "บ้านไอซ์ สาขาทองหล่อ", cuisine: "อาหารไทย", area: "ทองหล่อ",
    hue: 28, rating: 4.6, reviews: 1915, priceTHB: 600,
    priceLabel: "฿200-1,000 บาท", distanceKm: 2.0, capacity: 21, aiScore: 86,
    location: "115 ถ. ทองหล่อ", transit: "BTS ทองหล่อ", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=บ้านไอซ์+ทองหล่อ", wongnaiLink: "https://maps.google.com/maps/search/บ้านไอซ์+ทองหล่อ",
    breakdown: { reviews: 95, price: 77, distance: 68, capacity: 89, dataCompleteness: 85, uniqueness: 96 },
    radar: { "รสชาติ": 97, "ความคุ้มค่า": 83, "การบริการ": 94, "บรรยากาศ": 96, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,915 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อาหารใต้คอนเฟิร์ม",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r77", name: "MET CAFE", cuisine: "คาเฟ่และบรันช์", area: "ทองหล่อ",
    hue: 270, rating: 4.3, reviews: 228, priceTHB: 600,
    priceLabel: "฿200-1,000 บาท", distanceKm: 1.5, capacity: 16, aiScore: 82,
    location: "918 ซอย สุขุมวิท 55 ทองหล่อ", transit: "BTS ทองหล่อ", hours: "10:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=MET+CAFE+Thonglor+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/MET+CAFE+Thonglor",
    breakdown: { reviews: 87, price: 77, distance: 72, capacity: 81, dataCompleteness: 82, uniqueness: 93 },
    radar: { "รสชาติ": 93, "ความคุ้มค่า": 90, "การบริการ": 78, "บรรยากาศ": 84, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.3★ จาก 228 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "ตกแต่งด้วยกล้วยไม้",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r78", name: "Tulum Skybar", cuisine: "สเต๊กและอาหารตะวันตก", area: "ทองหล่อ",
    hue: 20, rating: 4.4, reviews: 1245, priceTHB: 500,
    priceLabel: "-", distanceKm: 0.6, capacity: 10, aiScore: 86,
    location: "559 ซอย สุขุมวิท 63", transit: "BTS ทองหล่อ", hours: "17:00-03:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Tulum+Skybar+Bangkok+Thonglor", wongnaiLink: "https://maps.google.com/maps/search/Tulum+Skybar+Thonglor",
    breakdown: { reviews: 94, price: 82, distance: 83, capacity: 80, dataCompleteness: 81, uniqueness: 97 },
    radar: { "รสชาติ": 85, "ความคุ้มค่า": 81, "การบริการ": 80, "บรรยากาศ": 84, "ความเข้ากันของกลุ่ม": 96 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,245 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "Skybar เปิดดึก",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r79", name: "Ombra Modern Tavern @Seenspace", cuisine: "อาหารอิตาเลียน", area: "ทองหล่อ",
    hue: 8, rating: 4.9, reviews: 241, priceTHB: 500,
    priceLabel: "-", distanceKm: 2.5, capacity: 8, aiScore: 88,
    location: "251/1 ซอย ทองหล่อ 13", transit: "BTS ทองหล่อ", hours: "17:00-01:30",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=Ombra+Modern+Tavern+Seenspace+Thonglor", wongnaiLink: "https://maps.google.com/maps/search/Ombra+Modern+Tavern+Thonglor",
    breakdown: { reviews: 96, price: 89, distance: 81, capacity: 74, dataCompleteness: 93, uniqueness: 99 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 95, "การบริการ": 94, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 93 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.9★ จาก 241 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "ไวน์บาร์ยอดนิยม",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r80", name: "Supanniga Eating Room (สาขาสอง)", cuisine: "อาหารไทย", area: "ทองหล่อ",
    hue: 28, rating: 4.4, reviews: 10, priceTHB: 800,
    priceLabel: "฿400-1,200 บาท", distanceKm: 2.5, capacity: 13, aiScore: 80,
    location: "ทองหล่อ ซอย 8", transit: "BTS ทองหล่อ", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Supanniga+Eating+Room+Thonglor+Soi+8", wongnaiLink: "https://maps.google.com/maps/search/Supanniga+Thonglor+2",
    breakdown: { reviews: 97, price: 65, distance: 67, capacity: 80, dataCompleteness: 82, uniqueness: 81 },
    radar: { "รสชาติ": 84, "ความคุ้มค่า": 77, "การบริการ": 84, "บรรยากาศ": 91, "ความเข้ากันของกลุ่ม": 93 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "ร้านอาหารไทยดัง",
      "ตั้งอยู่ย่านทองหล่อ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r81", name: "Gigi Eatery Asoke", cuisine: "อาหารอิตาเลียน", area: "อโศก",
    hue: 8, rating: 4.8, reviews: 3330, priceTHB: 900,
    priceLabel: "฿400-1,400 บาท", distanceKm: 1.9, capacity: 23, aiScore: 86,
    location: "28 ซอย สุขุมวิท 19", transit: "BTS อโศก/MRT สุขุมวิท", hours: "07:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Gigi+Eatery+Asoke+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Gigi+Eatery+Asoke",
    breakdown: { reviews: 94, price: 65, distance: 78, capacity: 88, dataCompleteness: 94, uniqueness: 89 },
    radar: { "รสชาติ": 97, "ความคุ้มค่า": 91, "การบริการ": 99, "บรรยากาศ": 97, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 3,330 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อิตาเลียนยอดนิยม",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r82", name: "แมดโมอา อโศก", cuisine: "อาหารนานาชาติ", area: "อโศก",
    hue: 140, rating: 4.8, reviews: 159, priceTHB: 500,
    priceLabel: "฿400-600 บาท", distanceKm: 1.5, capacity: 18, aiScore: 83,
    location: "139 สุขุมวิท 21 ซอย 1", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=แมดโมอา+อโศก+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/แมดโมอา+อโศก",
    breakdown: { reviews: 95, price: 90, distance: 67, capacity: 65, dataCompleteness: 90, uniqueness: 91 },
    radar: { "รสชาติ": 92, "ความคุ้มค่า": 94, "การบริการ": 89, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.8★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "รีซอตโต้อร่อย",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r83", name: "เคนชิน อิซากายะ อโศก", cuisine: "อาหารญี่ปุ่น", area: "อโศก",
    hue: 200, rating: 4.3, reviews: 1693, priceTHB: 500,
    priceLabel: "฿400-600 บาท", distanceKm: 1.4, capacity: 20, aiScore: 87,
    location: "155 ถนนอโศกมนตรี", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:00-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=เคนชิน+อิซากายะ+อโศก", wongnaiLink: "https://maps.google.com/maps/search/เคนชิน+อิซากายะ+อโศก",
    breakdown: { reviews: 94, price: 86, distance: 86, capacity: 87, dataCompleteness: 80, uniqueness: 85 },
    radar: { "รสชาติ": 85, "ความคุ้มค่า": 90, "การบริการ": 82, "บรรยากาศ": 85, "ความเข้ากันของกลุ่ม": 84 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,693 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อิซากายะยอดนิยม",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r84", name: "ปิง หูฉลาม อโศก", cuisine: "อาหารจีนและติ่มซำ", area: "อโศก",
    hue: 350, rating: 4.6, reviews: 1588, priceTHB: 1200,
    priceLabel: "฿1,000+ บาท", distanceKm: 2.3, capacity: 13, aiScore: 84,
    location: "137/3 ซอย สุขุมวิท 21", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=ปิง+หูฉลาม+อโศก", wongnaiLink: "https://maps.google.com/maps/search/ปิง+หูฉลาม+อโศก",
    breakdown: { reviews: 98, price: 50, distance: 89, capacity: 77, dataCompleteness: 93, uniqueness: 92 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 90, "การบริการ": 97, "บรรยากาศ": 94, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,588 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ขาห่านอบ หูฉลาม",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r85", name: "โรซาโน อิตาเลียน คูซีน", cuisine: "อาหารอิตาเลียน", area: "อโศก",
    hue: 8, rating: 4.5, reviews: 1137, priceTHB: 1200,
    priceLabel: "฿1,000+ บาท", distanceKm: 0.6, capacity: 15, aiScore: 77,
    location: "167 Sukhumvit Soi 21 ถนนอโศกมนตรี", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Rosano+Italian+Cuisine+Asok", wongnaiLink: "https://maps.google.com/maps/search/โรซาโน+อิตาเลียน+อโศก",
    breakdown: { reviews: 94, price: 57, distance: 76, capacity: 60, dataCompleteness: 85, uniqueness: 92 },
    radar: { "รสชาติ": 98, "ความคุ้มค่า": 79, "การบริการ": 91, "บรรยากาศ": 94, "ความเข้ากันของกลุ่ม": 97 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,137 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อิตาเลียนบรรยากาศดี",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r86", name: "isung (아이성)", cuisine: "อาหารเกาหลี", area: "อโศก",
    hue: 0, rating: 4.8, reviews: 986, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 0.6, capacity: 16, aiScore: 90,
    location: "203 ซอย สุขุมวิท 21", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=isung+Korean+Asoke+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/isung+Asoke",
    breakdown: { reviews: 99, price: 93, distance: 70, capacity: 83, dataCompleteness: 96, uniqueness: 99 },
    radar: { "รสชาติ": 99, "ความคุ้มค่า": 91, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 93 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.8★ จาก 986 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "จัมปงเกาหลียอดนิยม",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r87", name: "Tamaruya Honten Asoke", cuisine: "อาหารญี่ปุ่น", area: "อโศก",
    hue: 200, rating: 4.5, reviews: 269, priceTHB: 1000,
    priceLabel: "฿400-1,600 บาท", distanceKm: 1.2, capacity: 12, aiScore: 89,
    location: "อาคารฟิโก้ เพลส 18/8 ซอย สุขุมวิท 21", transit: "BTS อโศก/MRT สุขุมวิท", hours: "11:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Tamaruya+Honten+Asoke+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Tamaruya+Honten+Asoke",
    breakdown: { reviews: 98, price: 70, distance: 84, capacity: 88, dataCompleteness: 95, uniqueness: 96 },
    radar: { "รสชาติ": 89, "ความคุ้มค่า": 81, "การบริการ": 94, "บรรยากาศ": 92, "ความเข้ากันของกลุ่ม": 88 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.5★ จาก 269 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "ยากินิกุ เบียร์ 1 แถม 1",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r88", name: "LIB STORY Thai BBQ & Local Food", cuisine: "อาหารไทย", area: "อโศก",
    hue: 28, rating: 4.7, reviews: 360, priceTHB: 600,
    priceLabel: "฿200-1,000 บาท", distanceKm: 0.9, capacity: 25, aiScore: 86,
    location: "139 ซอย สุขุมวิท 21", transit: "BTS อโศก/MRT สุขุมวิท", hours: "16:30-23:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=LIB+STORY+Thai+BBQ+Asoke+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/LIB+STORY+Thai+BBQ+Asoke",
    breakdown: { reviews: 98, price: 72, distance: 72, capacity: 85, dataCompleteness: 88, uniqueness: 99 },
    radar: { "รสชาติ": 89, "ความคุ้มค่า": 85, "การบริการ": 90, "บรรยากาศ": 91, "ความเข้ากันของกลุ่ม": 93 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.7★ จาก 360 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "ราคาดีในย่านอโศก",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r89", name: "Origami Restaurant Sukhumvit 24", cuisine: "อาหารนานาชาติ", area: "อโศก",
    hue: 140, rating: 4.8, reviews: 246, priceTHB: 500,
    priceLabel: "-", distanceKm: 0.3, capacity: 9, aiScore: 93,
    location: "89/8 สุขุมวิท 24", transit: "BTS พร้อมพงษ์/อโศก", hours: "12:00-22:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=Origami+Restaurant+Sukhumvit+24", wongnaiLink: "https://maps.google.com/maps/search/Origami+Restaurant+Sukhumvit+24",
    breakdown: { reviews: 99, price: 82, distance: 81, capacity: 95, dataCompleteness: 99, uniqueness: 99 },
    radar: { "รสชาติ": 92, "ความคุ้มค่า": 93, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 92 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.8★ จาก 246 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "Borderless Cuisine",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r90", name: "Gigi Eatery Terminal 21", cuisine: "อาหารอิตาเลียน", area: "อโศก",
    hue: 8, rating: 4.7, reviews: 10, priceTHB: 800,
    priceLabel: "฿400-1,200 บาท", distanceKm: 2.3, capacity: 23, aiScore: 84,
    location: "Terminal 21 Asok", transit: "BTS อโศก/MRT สุขุมวิท", hours: "07:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Gigi+Eatery+Terminal+21+Asok", wongnaiLink: "https://maps.google.com/maps/search/Gigi+Eatery+Terminal21",
    breakdown: { reviews: 99, price: 72, distance: 68, capacity: 85, dataCompleteness: 84, uniqueness: 85 },
    radar: { "รสชาติ": 94, "ความคุ้มค่า": 84, "การบริการ": 98, "บรรยากาศ": 97, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.7★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "สาขาใน Terminal 21",
      "ตั้งอยู่ย่านอโศก เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r91", name: "โคเบะทนเทกิ พร้อมพงษ์", cuisine: "อาหารญี่ปุ่น", area: "พร้อมพงษ์",
    hue: 200, rating: 4.6, reviews: 1920, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 1.7, capacity: 17, aiScore: 87,
    location: "595 3-4 ซ. สุขุมวิท 33/1", transit: "BTS พร้อมพงษ์", hours: "11:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=โคเบะทนเทกิ+พร้อมพงษ์", wongnaiLink: "https://maps.google.com/maps/search/โคเบะทนเทกิ+พร้อมพงษ์",
    breakdown: { reviews: 99, price: 85, distance: 77, capacity: 79, dataCompleteness: 93, uniqueness: 86 },
    radar: { "รสชาติ": 90, "ความคุ้มค่า": 87, "การบริการ": 96, "บรรยากาศ": 88, "ความเข้ากันของกลุ่ม": 89 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,920 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "หมูทอดสไตล์ญี่ปุ่น",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r92", name: "Khao yiphun", cuisine: "อาหารญี่ปุ่น", area: "พร้อมพงษ์",
    hue: 200, rating: 4.4, reviews: 187, priceTHB: 150,
    priceLabel: "฿1-200 บาท", distanceKm: 2.4, capacity: 21, aiScore: 82,
    location: "B104 UBC2 591 ซ. สุขุมวิท 33", transit: "BTS พร้อมพงษ์", hours: "09:00-21:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Khao+yiphun+Sukhumvit+33", wongnaiLink: "https://maps.google.com/maps/search/Khao+yiphun+Phrom+Phong",
    breakdown: { reviews: 87, price: 96, distance: 68, capacity: 69, dataCompleteness: 88, uniqueness: 85 },
    radar: { "รสชาติ": 86, "ความคุ้มค่า": 78, "การบริการ": 89, "บรรยากาศ": 84, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "ราคาถูก คุ้มมาก",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r93", name: "Sarnies Cafe Sukhumvit", cuisine: "คาเฟ่และบรันช์", area: "พร้อมพงษ์",
    hue: 270, rating: 4.5, reviews: 1812, priceTHB: 500,
    priceLabel: "฿400-600 บาท", distanceKm: 0.4, capacity: 24, aiScore: 86,
    location: "1/39 ซอย สุขุมวิท 37", transit: "BTS พร้อมพงษ์", hours: "07:00-18:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Sarnies+Cafe+Sukhumvit+37", wongnaiLink: "https://maps.google.com/maps/search/Sarnies+Cafe+Sukhumvit",
    breakdown: { reviews: 95, price: 85, distance: 69, capacity: 88, dataCompleteness: 85, uniqueness: 88 },
    radar: { "รสชาติ": 92, "ความคุ้มค่า": 89, "การบริการ": 92, "บรรยากาศ": 88, "ความเข้ากันของกลุ่ม": 93 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,812 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "คาเฟ่บรันช์ยอดนิยม",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r94", name: "GaGa Udon House", cuisine: "อาหารญี่ปุ่น", area: "พร้อมพงษ์",
    hue: 200, rating: 4.8, reviews: 1602, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 2.3, capacity: 24, aiScore: 86,
    location: "6/5 H Building ซอยพร้อมศรี 2", transit: "BTS พร้อมพงษ์", hours: "10:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=GaGa+Udon+House+Phrom+Sri+2", wongnaiLink: "https://maps.google.com/maps/search/GaGa+Udon+House+Phrom+Phong",
    breakdown: { reviews: 99, price: 92, distance: 67, capacity: 65, dataCompleteness: 99, uniqueness: 95 },
    radar: { "รสชาติ": 97, "ความคุ้มค่า": 95, "การบริการ": 97, "บรรยากาศ": 98, "ความเข้ากันของกลุ่ม": 92 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,602 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อุด้งยอดนิยม mentaiko",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r95", name: "คิทเช่น นีงาตะ", cuisine: "อาหารญี่ปุ่น", area: "พร้อมพงษ์",
    hue: 200, rating: 4.4, reviews: 860, priceTHB: 300,
    priceLabel: "฿200-400 บาท", distanceKm: 2.5, capacity: 25, aiScore: 83,
    location: "47/3-4 ซ. สุขุมวิท 39", transit: "BTS พร้อมพงษ์", hours: "11:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=คิทเช่น+นีงาตะ+Sukhumvit+39", wongnaiLink: "https://maps.google.com/maps/search/Kitchen+Niigata+Sukhumvit",
    breakdown: { reviews: 84, price: 97, distance: 68, capacity: 81, dataCompleteness: 80, uniqueness: 91 },
    radar: { "รสชาติ": 91, "ความคุ้มค่า": 93, "การบริการ": 82, "บรรยากาศ": 82, "ความเข้ากันของกลุ่ม": 90 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.4★ จาก 860 รีวิว บ่งชี้ความคงเส้นคงวาด้านคุณภาพ",
      "อาหารญี่ปุ่นแท้",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r96", name: "Opera Italian Restaurant", cuisine: "อาหารอิตาเลียน", area: "พร้อมพงษ์",
    hue: 8, rating: 4.4, reviews: 1162, priceTHB: 2000,
    priceLabel: "฿2,000+ บาท", distanceKm: 0.5, capacity: 8, aiScore: 78,
    location: "1-2 ซ. สุขุมวิท 39", transit: "BTS พร้อมพงษ์", hours: "12:00-22:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=Opera+Italian+Restaurant+Sukhumvit+39", wongnaiLink: "https://maps.google.com/maps/search/Opera+Italian+Restaurant+Sukhumvit",
    breakdown: { reviews: 92, price: 40, distance: 78, capacity: 81, dataCompleteness: 80, uniqueness: 93 },
    radar: { "รสชาติ": 95, "ความคุ้มค่า": 93, "การบริการ": 90, "บรรยากาศ": 87, "ความเข้ากันของกลุ่ม": 85 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 1,162 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "อิตาเลียน Fine Dining",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r97", name: "TEN-SHOW Live Kitchen", cuisine: "อาหารญี่ปุ่น", area: "พร้อมพงษ์",
    hue: 200, rating: 4.8, reviews: 199, priceTHB: 1200,
    priceLabel: "฿1,000+ บาท", distanceKm: 1.6, capacity: 11, aiScore: 81,
    location: "12 ซ. สุขุมวิท 24", transit: "BTS พร้อมพงษ์", hours: "11:30-22:00",
    groupFriendly: false,
    gmapsLink: "https://maps.google.com/?q=TEN-SHOW+Live+Kitchen+Sukhumvit+24", wongnaiLink: "https://maps.google.com/maps/search/TEN-SHOW+Live+Kitchen+Sukhumvit",
    breakdown: { reviews: 95, price: 57, distance: 67, capacity: 69, dataCompleteness: 99, uniqueness: 99 },
    radar: { "รสชาติ": 95, "ความคุ้มค่า": 95, "การบริการ": 99, "บรรยากาศ": 99, "ความเข้ากันของกลุ่ม": 99 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.8★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "Open Kitchen ญี่ปุ่น",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r98", name: "โกจิคิทเช่น + บาร์", cuisine: "อาหารนานาชาติ", area: "พร้อมพงษ์",
    hue: 140, rating: 4.6, reviews: 4632, priceTHB: 2000,
    priceLabel: "฿2,000+ บาท", distanceKm: 1.0, capacity: 22, aiScore: 85,
    location: "Bangkok Marriott Marquis Queen's Park 199 ซ. สุขุมวิท 22", transit: "BTS พร้อมพงษ์", hours: "06:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Goji+Kitchen+Bar+Bangkok+Marriott+Marquis", wongnaiLink: "https://maps.google.com/maps/search/Goji+Kitchen+Marriott+Sukhumvit",
    breakdown: { reviews: 97, price: 40, distance: 86, capacity: 93, dataCompleteness: 87, uniqueness: 99 },
    radar: { "รสชาติ": 97, "ความคุ้มค่า": 90, "การบริการ": 92, "บรรยากาศ": 91, "ความเข้ากันของกลุ่ม": 87 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 4,632 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "บุฟเฟต์โรงแรม 5 ดาว",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r99", name: "Bistro M", cuisine: "อาหารนานาชาติ", area: "พร้อมพงษ์",
    hue: 140, rating: 4.4, reviews: 174, priceTHB: 900,
    priceLabel: "฿800-1,000 บาท", distanceKm: 1.0, capacity: 25, aiScore: 80,
    location: "Ground Floor Marriott Executive Apartments 90 Sukhumvit Park", transit: "BTS พร้อมพงษ์", hours: "05:30-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=Bistro+M+Marriott+Executive+Apartments+Bangkok", wongnaiLink: "https://maps.google.com/maps/search/Bistro+M+Sukhumvit+Park",
    breakdown: { reviews: 87, price: 63, distance: 67, capacity: 78, dataCompleteness: 85, uniqueness: 99 },
    radar: { "รสชาติ": 91, "ความคุ้มค่า": 90, "การบริการ": 93, "บรรยากาศ": 93, "ความเข้ากันของกลุ่ม": 84 },
    sources: ["Google Maps"],
    reasons: [
      "คะแนน 4.4★ — ลูกค้าชื่นชมความสดใหม่และรสชาติ",
      "อาหารโรงแรม หลากหลาย",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
  {
    id: "r100", name: "Khao Gaeng Jake Puey Terminal 21", cuisine: "อาหารไทย", area: "พร้อมพงษ์",
    hue: 28, rating: 4.6, reviews: 2100, priceTHB: 150,
    priceLabel: "฿1-200 บาท", distanceKm: 1.6, capacity: 22, aiScore: 89,
    location: "Terminal 21 Asok ชั้น G", transit: "BTS พร้อมพงษ์", hours: "09:00-22:00",
    groupFriendly: true,
    gmapsLink: "https://maps.google.com/?q=ข้าวแกงเจ๊ปุ้ย+Terminal+21+Asok", wongnaiLink: "https://maps.google.com/maps/search/Khao+Gaeng+Jake+Puey+Terminal+21",
    breakdown: { reviews: 92, price: 94, distance: 88, capacity: 88, dataCompleteness: 83, uniqueness: 84 },
    radar: { "รสชาติ": 93, "ความคุ้มค่า": 88, "การบริการ": 94, "บรรยากาศ": 97, "ความเข้ากันของกลุ่ม": 94 },
    sources: ["Google Maps"],
    reasons: [
      "รีวิวกว่า 2,100 รายการยืนยันความนิยมและคุณภาพสม่ำเสมอ",
      "ข้าวแกงชื่อดังราคาถูก",
      "ตั้งอยู่ย่านพร้อมพงษ์ เดินทางสะดวกด้วยระบบขนส่งสาธารณะ",
    ],
  },
];

// AI pipeline stages shown in the workflow visualization
const WORKFLOW_STAGES = [
  { id: "input", title: "รับข้อมูลจากผู้ใช้", desc: "บันทึกพื้นที่ จำนวนคน งบประมาณ และประเภทอาหาร", icon: "cursor", metric: "4 พารามิเตอร์" },
  { id: "search", title: "ค้นหาร้านอาหาร", desc: "ค้นหาร้านจากฐานข้อมูล Wongnai + Google Maps", icon: "search", metric: "100 ร้าน" },
  { id: "reviews", title: "รวบรวมรีวิว", desc: "รวบรวมรีวิวจากแหล่งที่น่าเชื่อถือ", icon: "messages", metric: "38,400 รีวิว" },
  { id: "clean", title: "ทำความสะอาดข้อมูล", desc: "ลบข้อมูลซ้ำและกรองสัญญาณรบกวน", icon: "filter", metric: "−61% สัญญาณรบกวน" },
  { id: "analyze", title: "วิเคราะห์ด้วย AI", desc: "วิเคราะห์ความรู้สึกและความเหมาะกับกลุ่มของแต่ละร้าน", icon: "brain", metric: "โมเดล v4" },
  { id: "score", title: "คำนวณคะแนนถ่วงน้ำหนัก", desc: "ถ่วงน้ำหนัก รีวิว · ราคา · ระยะทาง · ความจุ · ข้อมูล · เอกลักษณ์", icon: "sliders", metric: "6 ปัจจัย" },
  { id: "rank", title: "จัดอันดับ", desc: "เรียงลำดับร้านตามคะแนน AI รวม", icon: "list", metric: "Top 10" },
  { id: "recommend", title: "แนะนำร้าน", desc: "เลือก 3 ร้านที่ดีที่สุดพร้อมเหตุผล", icon: "sparkles", metric: "Top 3" },
  { id: "report", title: "สรุปผล", desc: "รวบรวมรายงานการตัดสินใจในรูปแบบ HTML", icon: "file", metric: "1 รายงาน" },
];

// scoring weights used in the weighted-score breakdown viz
const SCORE_WEIGHTS = [
  { key: "reviews", label: "Rating & Review Quality", weight: 25, hue: "accent" },
  { key: "capacity", label: "Group Suitability", weight: 20, hue: "accent2" },
  { key: "price", label: "Price Suitability", weight: 15, hue: "warn" },
  { key: "distance", label: "Travel Convenience", weight: 15, hue: "pos" },
  { key: "dataCompleteness", label: "Data Completeness", weight: 15, hue: "accent" },
  { key: "uniqueness", label: "Uniqueness/Experience", weight: 10, hue: "accent2" },
];

const DATA_SOURCES = [
  { id: "gmaps", name: "Google Maps", detail: "คะแนน ที่ตั้ง และความนิยมแบบเรียลไทม์ (50 ร้าน)", glyph: "pin", records: "21,800 รีวิว" },
  { id: "wongnai", name: "Wongnai", detail: "รีวิวร้านอาหารไทยและเมนูท้องถิ่น (50 ร้าน)", glyph: "star", records: "12,300 รีวิว" },
];

Object.assign(window, {
  AREAS, FOOD_CATEGORIES, RESTAURANTS, WORKFLOW_STAGES, SCORE_WEIGHTS, DATA_SOURCES,
});
